# -*- coding: utf-8 -*-
from .funutils import findLibrary, createLibrary
# DO NOT EDIT
#This file was generated by ./funutils.py fluidsynth.h FluidSynth libfluidsynth-2 libfluidsynth-1 libfluidsynth fluidsynth

lib_names = ['libfluidsynth-2', 'libfluidsynth-1', 'libfluidsynth', 'fluidsynth']
lib_path = findLibrary('FluidSynth', lib_names)
cfunc = createLibrary(lib_path)

from ctypes import c_char_p, c_double, c_int, c_void_p

new_fluid_settings = cfunc('new_fluid_settings', c_void_p)
delete_fluid_settings = cfunc('delete_fluid_settings', None,
  ('settings', c_void_p))
new_fluid_synth = cfunc('new_fluid_synth', c_void_p,
  ('settings', c_void_p))
delete_fluid_synth = cfunc('delete_fluid_synth', None,
  ('synth', c_void_p))
fluid_settings_setstr = cfunc('fluid_settings_setstr', c_int,
  ('settings', c_void_p), ('name', c_char_p), ('str', c_char_p))
fluid_settings_setnum = cfunc('fluid_settings_setnum', c_int,
  ('settings', c_void_p), ('name', c_char_p), ('val', c_double))
fluid_settings_setint = cfunc('fluid_settings_setint', c_int,
  ('settings', c_void_p), ('name', c_char_p), ('val', c_int))
fluid_synth_sfload = cfunc('fluid_synth_sfload', c_int,
  ('synth', c_void_p), ('filename', c_char_p), ('update_midi_presets', c_int))
fluid_synth_sfunload = cfunc('fluid_synth_sfunload', c_int,
  ('synth', c_void_p), ('sfid', c_int), ('update_midi_presets', c_int))
fluid_synth_program_select = cfunc('fluid_synth_program_select', c_int,
  ('synth', c_void_p), ('chan', c_int), ('sfid', c_int), ('bank', c_int), ('preset', c_int))
fluid_synth_noteon = cfunc('fluid_synth_noteon', c_int,
  ('synth', c_void_p), ('chan', c_int), ('key', c_int), ('vel', c_int))
fluid_synth_noteoff = cfunc('fluid_synth_noteoff', c_int,
  ('synth', c_void_p), ('chan', c_int), ('key', c_int))
fluid_synth_write_s16 = cfunc('fluid_synth_write_s16', None,
  ('synth', c_void_p), ('len', c_int), ('lbuf', c_void_p), ('loff', c_int), ('lincr', c_int), ('rbuf', c_void_p), ('roff', c_int), ('rincl', c_int))
new_fluid_audio_driver = cfunc('new_fluid_audio_driver', c_void_p,
  ('settings', c_void_p), ('synth', c_void_p))
delete_fluid_audio_driver = cfunc('delete_fluid_audio_driver', None,
  ('driver', c_void_p))
